[package]
name = "slicing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
euclid = "0.22.6"
threemf = { path = "../threemf" }